apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: default-route-openshift-image-registry.apps.rm2.thpm.p1.openshiftapps.com/tercioo-gabriel-dev/frontend:v5
          ports:
            - containerPort: 5173
